server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanjingchang/springcloud-demo.git
          searchPaths: config
          username: yanjingchang
          password: Github_7920
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

