###查询全部
GET http://localhost:8010/student/findall
Accept: application/json

###根据id查询
GET http://localhost:8010/student/findbyid/3
Accept: application/json

###增加学生
POST http://localhost:8010/student/save
Accept: application/json
Content-Type: application/json; charset=UTF-8

{
  "id": 4,
  "name": "颜景昌",
  "gender": "男"
  }

###修改
PUT http://localhost:8010/student/update
Accept: application/json
Content-Type: application/json; charset=UTF-8

{
  "id": 4,
  "name": "liamyan",
  "gender": "男"
  }

###删除
DELETE http://localhost:8010/student/delete/2
Accept: application/json

###